### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by JBMJBM** [DanielGallo/GivEnergy-Scriptable-Widget#1]
I keep getting an error on line 248:33: 

Type Error: undefined is not an object (evaluating 'attribute.state')

Any way to fix this?

**Comment by DanielGallo** [comment]
Hi! This means one of the attributes can't be found in Home Assistant (perhaps there's a name mismatch). 

I've just published a new version of the code with some error logging - when you try and run the widget in Scriptable it will log an error listing the specific attribute that can't be found. Please try using the new version of the code to pinpoint which attribute it's not able to find. 

If the issue is with the `sensor.daily_energy_peak` and `sensor.daily_energy_offpeak` attributes, try changing those attributes to `sensor.utility_meter_peak` and `sensor.utility_meter_offpeak` (on lines 102 and 114).
